FROM gradle:latest as builder
COPY build.gradle.kts .
COPY gradle.properties .
COPY gradlew .
COPY gradlew.bat .
COPY src ./src
RUN gradle clean build

FROM openjdk:8-jre-alpine
COPY --from=builder /home/gradle/build/libs/gradle-0.0.1.jar /ktor-league.jar
CMD [ "java", "-jar", "-Djava.security.egd=file:/dev/./urandom", "/ktor-league.jar" ]